### ISSUE TITLE
Using 'dateLimit' option triggers moment deprecation warning

### ISSUE THREAD

**Issue by devillexio** [fragaria/angular-daterangepicker#112]
When using the _dateLimit_ option, moment.js logs a deprecation warning.

Excerpt of config:

```
{
  ...
  dateLimit: {
    months: '12'
  },
  ...
}
```

Deprecation warning logged by moment.js:

```
Deprecation warning: moment construction falls back to js Date. This is discouraged and will be removed in upcoming major release. Please refer to https://github.com/moment/moment/issues/1407 for more info.
Error
    at Function.createFromInputFallback (http://localhost:3000/bower_components/moment/moment.js:746:36)
    at configFromInput (http://localhost:3000/bower_components/moment/moment.js:1365:32)
    at prepareConfig (http://localhost:3000/bower_components/moment/moment.js:1340:13)
    at createFromConfig (http://localhost:3000/bower_components/moment/moment.js:1307:44)
    at createLocalOrUTC (http://localhost:3000/bower_components/moment/moment.js:1385:16)
    at local__createLocal (http://localhost:3000/bower_components/moment/moment.js:1389:16)
    at Moment.isAfter (http://localhost:3000/bower_components/moment/moment.js:1847:47)
    at new DateRangePicker (http://localhost:3000/bower_components/bootstrap-daterangepicker/daterangepicker.js:310:73)
    at HTMLInputElement.<anonymous> (http://localhost:3000/bower_components/bootstrap-daterangepicker/daterangepicker.js:1488:40)
    at Function.jQuery.extend.each (http://localhost:3000/bower_components/jquery/dist/jquery.js:374:23)
```

**Comment by raygerrard** [comment]
This is likely due to a date in the format "DD/MM/YYYY" being passed to the moment constructor without format. I cannot replicate this issue however, can you produce a plunkr?

**Comment by devillex** [comment]
Hi. Unfortunately, I'm not sure how to convert my code into a plunkr, but I can share some additional information.

Options of DateRangePicker:
```javascript
initDateRangePicker() {
    const vm = this;
    const date = {
      startDate: moment().subtract(14, 'days'),
      endDate: moment()
    };

    const options = {
      opens: 'left',
      linkedCalendars: false,
      buttonClasses: ['btn', 'btn-sm'],
      applyClass: 'btn btn-sm',
      cancelClass: 'btn btn-sm',
      dateLimit: {
        months: '12'
      },
      locale: {
        cancelLabel: 'Clear'
      },
      eventHandlers: {
        'apply.daterangepicker': (ev) => {
          const dateFormat = 'YYYY-MM-DD';
          const fd = ev.model.startDate;
          const td = ev.model.endDate;
          vm.$log.debug('Date range picker apply clicked. Date range from \'' + fd.format(dateFormat) + '\' to \'' +
            td.format(dateFormat) + '\'.');
          // update values for filtering
          vm.$scope.campaignDateRangeStart = fd;
          vm.$scope.campaignDateRangeEnd = td;
          // reload table data
          vm.dtInstance.rerender();
        },
        'cancel.daterangepicker': () => {
          vm.$log.debug('Date range picker cancel (clear) clicked. Resetting range start and end date.');
          // reset values
          vm.datePicker.date = {
            startDate: moment().subtract(14, 'days'),
            endDate: moment()
          };
          delete vm.$scope.campaignDateRangeStart;
          delete vm.$scope.campaignDateRangeEnd;
          // reload table data
          vm.dtInstance.rerender();
        }
      },
      ranges: {
        'Today': [moment(), moment()],
        'Yesterday': [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
        'This quarter': [moment().startOf('quarter'), moment()],
        'Last quarter': [moment().subtract(1, 'Q').startOf('quarter'), moment().subtract(1, 'Q').endOf('quarter')],
        'This year': [moment().startOf('year'), moment()]
      }
    };

    vm.datePicker = {
      date,
      options
    };
  }
```

Bower dependencies:
```json
"dependencies": {
    "angular-animate": "~1.4.0",
    "angular-cookies": "~1.4.0",
    "angular-touch": "~1.4.0",
    "angular-sanitize": "~1.4.0",
    "jquery": "~2.1.4",
    "angular-resource": "~1.4.0",
    "angular-route": "~1.4.0",
    "bootstrap": "~3.3.4",
    "angular-bootstrap": "~0.13.0",
    "malarkey": "yuanqing/malarkey#~1.3.0",
    "toastr": "~2.1.1",
    "moment": "~2.10.3",
    "animate.css": "~3.3.0",
    "angular": "~1.4.0",
    "mazhekin-my-fontello": "~0.0.1",
    "angular-datatables": "~0.5.0",
    "angular-daterangepicker": "~0.2.0",
    "angular-wizard": "~0.5.5"
  },
  "devDependencies": {
    "angular-mocks": "~1.4.0"
  }
```

Please let me know if anything else would be helpful.

**Comment by raygerrard** [comment]
If you have a working example somewhere I can take a look.

**Comment by ogazioglu** [comment]
+1

I use
- daterangepicker v2.1.17
- moment v2.11.2
- jquery v2.2.0

I have faced with this issue, too. I use the option below:  

    locale: {
        format: 'DD[.]MM[.]YYYY',
        ...
    },
    dateLimit: {
        months: 3
    },
    ...

Here is my exception

    Deprecation warning: moment construction falls back to js Date. This is discouraged and will be removed in upcoming major release. Please refer to https://github.com/moment/moment/issues/1407 for more info.
    Arguments: [object Object]
    Error
        at Function.createFromInputFallback (http://localhost:51295/Scripts/moment.js?2.11.2:850:105)
        at configFromInput (http://localhost:51295/Scripts/moment.js?2.11.2:1485:32)
        at prepareConfig (http://localhost:51295/Scripts/moment.js?2.11.2:1456:13)
        at createFromConfig (http://localhost:51295/Scripts/moment.js?2.11.2:1423:44)
        at createLocalOrUTC (http://localhost:51295/Scripts/moment.js?2.11.2:1505:16)
        at local__createLocal (http://localhost:51295/Scripts/moment.js?2.11.2:1509:16)
        at Moment.isAfter (http://localhost:51295/Scripts/moment.js?2.11.2:1998:52)
        at new DateRangePicker (http://localhost:51295/Scripts/daterangepicker.js?2.1.17:310:73)
        at HTMLInputElement.<anonymous> (http://localhost:51295/Scripts/daterangepicker.js?2.1.17:1519:40)
        at Function.n.extend.each (http://localhost:51295/Scripts/jquery-2.2.0.min.js:2:2773)

Everthing that I used until today work but I got this warning for dateLimit option.
Moment works even if it warns by the way.

**Comment by antonellof** [comment]
The error start at line 310:

var maxDate = this.maxDate;
                if (this.dateLimit && start.clone().add(this.dateLimit).isAfter(maxDate))
                    maxDate = start.clone().add(this.dateLimit);
                if (maxDate && end.isAfter(maxDate))
                    end = maxDate.clone();

The moment add function call  deprecation warning.
I solved using dateLimit in unix format. eg:

{
            locale: {
                applyClass: 'btn-success',
                applyLabel: "Conferma",
                fromLabel: "Da",
                format: "DD-MM-YYYY",
                toLabel: "A",
                cancelLabel: 'Annulla',
                customRangeLabel: 'Periodo Personalizzato'
            },
            ranges: {
                'SETTIMANA': [moment().subtract(6, 'days'), moment()],
                'MESE': [moment().subtract(29, 'days'), moment()],
                'TRIMESTRE': [moment().subtract(89, 'days'), moment()]
            },
            dateLimit: 7776000000
        }

For 90 days = 7776000000 ( 90days*24hours*60mins*60sec*1000millisec)
